### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by anta40** [zmxv/react-native-sound#874]
I'm still on RN 0.71.0. After installing react-native-sound (0.13.0), the project failed to build on Android:

```
$ yarn android:dev
> Task :react-native-sound:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
520 actionable tasks: 18 executed, 502 up-to-date
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:1778:24: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"
        return (typeof DebuggerInternal !== 'undefined' && DebuggerInternal.shouldPauseOnThrow === true
                       ^~~~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:4994:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"
      setTimeout(function () {
      ^~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:2968:108: warning: the variable "nativeFabricUIManager" was not declared in function "onChange"
      (fromOrTo = fromOrTo && fromOrTo.stateNode) && fromOrTo.canonical._internalInstanceHandle ? (from && nativeFabricUIManager.setIsJSResponder(from.stateNode.node, false, blockNativeResponder || false), to && nativeFabricUIManager.setIsJSResponder(to.stateNode.node, true, blockNativeResponder || false)) : null !== to ? _$$_REQUIRE(_dependencyMap[2]).UIManager.setJSResponder(to.stateNode.canonical._nativeTag, blockNativeResponder) : _$$_REQUIRE(_dependencyMap[2]).UIManager.clearJSResponder();
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:3575:21: warning: the variable "clearTimeout" was not declared in anonymous function " 105#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:7325:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 105#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:8069:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:8280:16: warning: the variable "AggregateError" was not declared in function "getAggregateError"
    if (typeof AggregateError === 'function') {
               ^~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:11005:12: warning: the variable "fetch" was not declared in anonymous function " 312#"
    fetch: fetch,
    
...
...
...

/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:194363:22: warning: the variable "_measurePaper" was not declared in function "measurePaper"
      var measured = _measurePaper(viewTag);
                     ^~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:194439:7: warning: the variable "_scrollToPaper" was not declared in function "scrollToPaper"
      _scrollToPaper(viewTag, x, y, animated);
      ^~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:194486:7: warning: the variable "_setGestureState" was not declared in function "setGestureStateNative"
      _setGestureState(handlerTag, newState);
      ^~~~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:196232:7: warning: the variable "_removeFromPropsRegistry" was not declared in function "removeFromPropsRegistryOnUI"
      _removeFromPropsRegistry(viewTags);
      ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:283425:42: warning: the variable "Element" was not declared in function "equal"
      if (hasElementType && a instanceof Element && b instanceof Element) return a === b;
                                         ^~~~~~~
/Users/anta40/Codes/Work/oa-mobile/android/app/build/ASSETS/createBundleDevelopmentDebugJsAndAssets/index.android.bundle:327156:20: warning: the variable "WeakRef" was not declared in anonymous function " 9143#"
  var Ref = typeof WeakRef !== "undefined" ? WeakRef : StrongRef;
                   ^~~~~~~
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/anta40/Codes/Work/oa-mobile/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/Sound.kt: (12, 34): Unresolved reference: BridgeReactContext
e: /Users/anta40/Codes/Work/oa-mobile/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/Sound.kt: (33, 18): Not enough information to infer type variable T
e: /Users/anta40/Codes/Work/oa-mobile/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/Sound.kt: (33, 30): Unresolved reference: RCTDeviceEventEmitter
e: /Users/anta40/Codes/Work/oa-mobile/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/SoundPackage.kt: (33, 7): No value passed for parameter 'p6'

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-sound:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

Is there a solution, preferrably without upgrading RN?

**Comment by RomualdPercereau** [comment]
Hello @anta40, 

For react-native 0.71 I strongly suggest you to use [v0.11.2](https://github.com/zmxv/react-native-sound/releases/tag/v0.11.2).

**Comment by anta40** [comment]
Ah indeed. I didn't read the doc carefully. Yes, 0.11.2 works fine on RN 0.71
