### ISSUE TITLE
**ERROR** build iOS fail "use of undeclared identifier 'JS'"

### ISSUE THREAD

**Issue by IvanMod4** [zmxv/react-native-sound#865]
:beetle: **Description**

Trying to do the ios build fails with the error "use of undeclared identifier 'JS'".

The error is on line 180 of the RNSound.mm file:

`RCT_EXPORT_METHOD(prepare:(NSString *)fileName key:(double)key options:(JS::NativeSoundIOS::SoundOptionTypes &)options callback:(RCTResponseSenderBlock)callback ) {`

<img width="1345" height="295" alt="Image" src="https://github.com/user-attachments/assets/e216f4cd-131d-4efc-b047-afbbeb21bc5a" />

**Is your issue with...**

- [X] iOS
- [ ] Android
- [ ] Windows

**Are you using...**

- [X] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound: 0.12.0
- React Native: 0.80.1
- iOS: 18.5

**Comment by vishalnaikawadi** [comment]
For me, going back to `0.11.2` worked on RN 0.80.0, iOS 18.2.

**Comment by reubenDysarz** [comment]
+1 - same here for ios

**Comment by bhavinatharva** [comment]
facing same

**Comment by eyupdogan** [comment]
This patch fixes compatibility and runtime issues in the `react-native-sound` module.

It includes the following changes:

Fixes a crash in the native iOS implementation (`RNSound.mm`) caused by missing or incorrectly exported methods.
Resolves a type mismatch in the prepare method by aligning the Objective-C implementation with the expected JavaScript interface.
Updates the JavaScript `index.ts` to use direct native constants instead of the deprecated `getDirectories()` method.

[react-native-sound+0.12.0.patch](https://github.com/user-attachments/files/27714595/react-native-sound%2B0.12.0.patch)
