### ISSUE TITLE
Does not build with RN 0.66.4 and Xcode 13.2

### ISSUE THREAD

**Issue by teknologista** [zmxv/react-native-sound#773]
:beetle: **Description**

Getting the following build errors: 

```
node_modules/react-native-sound/RNSound/RNSound.m:231:44: Implicit declaration of function 'RCTJSErrorFromNSError' is invalid in C99

node_modules/react-native-sound/RNSound/RNSound.m:231:44: Conflicting types for 'RCTJSErrorFromNSError'
Declaration of 'RCTJSErrorFromNSError' must be imported from module 'React.RCTUtils' before it is required

node_modules/react-native-sound/RNSound/RNSound.m:231:44: Declaration of 'RCTJSErrorFromNSError' must be imported from module 'React.RCTUtils' before it is required

node_modules/react-native-sound/RNSound/RNSound.m:231:44: Declaration of 'RCTJSErrorFromNSError' must be imported from module 'React.RCTLog' before it is required
```

:beetle: **What is the observed behavior?**

Build fails on Xcode 13.2

:beetle: **What is the expected behavior?**

:beetle: **Please post your code:**

```js
// Please post your code
```

:bulb: **Does the problem have a test case?**

 

:bulb: **Possible solution**

:bulb: **Is there a workaround?**

:bulb: **If the bug is confirmed, would you be willing to create a pull request?**

**Is your issue with...**

- [ X] iOS
- [ ] Android
- [ ] Windows

**Are you using...**

- [X ] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound:  0.11.1
- React Native: 0.66.4
- iOS: 15
- Android:
- Windows:
- Xcode: 13.2
**Does the problem occur on...**

- [ X] Simulator
- [x] Device

**If your problem is happening on a device, which device?**

- Device:

**Comment by teknologista** [comment]
Solved by uninstalling and reinstalling

**Comment by teknologista** [comment]
@technyx-ali-rehman  You need to remove React conditional imports

in RNSound file in Xcode:

Replace 

```
#if __has_include("RCTUtils.h")
#import "RCTUtils.h"
#else
#import <React/RCTUtils.h>
#endif
```


with 

`
#import <React/RCTUtils.h>
`

See here for details on the issue:

https://github.com/LinusU/react-native-get-random-values/pull/33/commits/30267ff4e9b5e93136cc935cf0370d8a09dd3aee
