### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by jalal246** [zmxv/react-native-sound#387]
Hi, this may be so easy to solve but actually i stuck with error after linking the project.

dependencies:
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-sound": "^0.10.7",

here's the debug info i got
```
:react-native-sound:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:43: error: cannot find symbol
    final ReactContext reactContext = this.context;
          ^
  symbol:   class ReactContext
  location: class RNSoundModule
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:207: error: incompatible types: Double cannot be converted to Integer
      setOnPlay(false, key);
                       ^
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:223: error: incompatible types: Double cannot be converted to Integer
      this.focusedPlayerKey = key;
                              ^
error: incompatible types: Double cannot be converted to Integer
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:260: error: incompatible types: Double cannot be converted to Integer
    setOnPlay(true, key);
                    ^
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:284: error: incomparable types: Double and Integer
    if (!this.mixWithOthers && key == this.focusedPlayerKey) {
                                   ^
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:308: error: incomparable types: Double and Integer
      if (!this.mixWithOthers && key == this.focusedPlayerKey) {
                                     ^
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:416: error: incompatible types: Integer cannot be converted to Double
              this.pause(this.focusedPlayerKey, null);
                             ^
Path:\\node_modules\react-native-sound\android\src\main\java\com\zmxv\RNSound\RNSoundModule.java:420: error: incompatible types: Integer cannot be converted to Double
              this.play(this.focusedPlayerKey, null);
                            ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
9 errors
:react-native-sound:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sound:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```
Thanks

**Comment by dannyyaou** [comment]
+1

**Comment by HessiPard** [comment]
+1

**Comment by GeoffreyPlitt** [comment]
Same, how do we get past this?

**Comment by jalal246** [comment]
@GeoffreyPlitt  i struggled a lot unfortunately i ended using another package

**Comment by HessiPard** [comment]
Just restrict the version in package.json to 0.10.5 without ^

**Comment by jalal246** [comment]
@HessiPard It works well with 0.10.5
