### ISSUE TITLE
Version 0.12.0 (New Architecture) breaks local files usage

### ISSUE THREAD

**Issue by M-i-k-e-l** [zmxv/react-native-sound#866]
:beetle: **Description**

After upgrading to version `0.12.0` in order to get support for the New Architecture, using a local file (`require('./myExcellentSong.mp3')` fails to load.

:beetle: **What is the observed behavior?**

In my usage I do not get a call to the `callback` (provided in the `constructor`).

I've created a new project (RN 0.77.2 with rn-sound@0.12.0) that uses the `SoundPlayer` from your example app (with small modifications); there I see the following error:
```
TypeError: filename.startsWith is not a function (it is undefined)
```
Coming from [this line](https://github.com/zmxv/react-native-sound/blob/02594428ec20c916dce492129d21e4ef2a10b018/src/index.ts#L74), if I add `?.` I get an alert with `resource not found`.

:beetle: **What is the expected behavior?**

The same code works on an older project (RN 0.73.11 with rn-sound@0.11.2)

:beetle: **Please post your code:**

[Link to gist](https://gist.github.com/M-i-k-e-l/1097f25d91a87b6f0231c6626df45415)
* I did not add a real song due to copyright issues

:bulb: **Does the problem have a test case?**

 
Yes, flow:
1. `npx @react-native-community/cli@latest init --version 0.77.2 sound77`
2. Add the following to `package.json`:
```
"@react-native-community/slider": "^4.5.5",
"react-native-sound": "0.11.2"
```
3. `yarn`
4. `yarn start`
5. Change `App.tsx` to [your file](https://github.com/zmxv/react-native-sound/blob/master/example/App.tsx)
6. Add `SoundPlayer.tsx` from my gist
7. Add a local mp3 file
8. Install (I've tested on Android)

Note: in my original project iOS it not working as well

:bulb: **Possible solution**

:bulb: **Is there a workaround?**

:bulb: **If the bug is confirmed, would you be willing to create a pull request?**

**Is your issue with...**

- [x] iOS
- [x] Android
- [ ] Windows

**Are you using...**

- [x] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound: 0.12.0
- React Native: 0.77.2
- iOS: 16.4
- Android: 14 (simulator) / 16 (real)
- Windows:

**Does the problem occur on...**

- [x] Simulator
- [x] Device

**If your problem is happening on a device, which device?**

- Device: Pixel 9a

**Comment by arslan-tahir715** [comment]
I'm getting the exact same issue

**Comment by scosmanagraz** [comment]
You have to update your implementation of react-native-sound. You must change your Sound implementation to the way it's shown on the readme here: [Basic Usage](https://github.com/zmxv/react-native-sound?tab=readme-ov-file#basic-usage) . 

In the past, the Sound constructor first parameter expected a `require('./myExcellentSound.mp3');`, now the first parameter must be of type `string`.

**Comment by M-i-k-e-l** [comment]
Thanks @scosmanagraz, that does work.
