### ISSUE TITLE
 _reactNativeSound2.default.setCategory is not a function

### ISSUE THREAD

**Issue by jwilbert** [zmxv/react-native-sound#110]
Hi - 

I just installed React Native Sounds and it seems to work fine. Though, when I try to get the Background Mode working, I get the following error:  
>  _reactNativeSound2.default.setCategory is not a function

My implementation is relatively standard:
```
import Sound from 'react-native-sound';

export default class playTrack extends Component {
  constructor(props) {
    super(props);
    Sound.setCategory('Ambient', true);
    
    this.play = new Sound(props.trackPath, Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error);
      } else { // loaded successfully
        console.log('duration in seconds: ' + this.play.getDuration() +
        'number of channels: ' + this.play.getNumberOfChannels());
      }
    });
  }
```

Can someone troubleshoot?

**Comment by zmxv** [comment]
Are you calling the setCategory function on Android? It's an iOS-only feature.

**Comment by jwilbert** [comment]
Hi @zmxv, 
Sorry, I should have mentioned that I work on iOS & react-native 0.38.0

**Comment by Ali-Ayyad** [comment]
@zmxv  same problem here as well.

**Comment by benvium** [comment]
@jwilbert What you have is supposed to work and works for me on https://github.com/zmxv/react-native-sound-demo/blob/master/main.js.

However, can you try instead:

```
this.play = new Sound(props.trackPath, Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error);
      } else { // loaded successfully
        console.log('duration in seconds: ' + this.play.getDuration() +
        'number of channels: ' + this.play.getNumberOfChannels());
      }
    });
this.play.setCategory('Ambient', true);
```

i.e. using the version of setCategory on the sound instance.

Also are you definitely using the 0.9.0 version? Another thing to try is installing from master rather than the npm release.  Let me know if any of this helps.

**Comment by jwilbert** [comment]
@benvium You were right. For some reason npm updated the module only to 0.8.3. I installed now 0.9.0 from GitHub.  I also changed the code according to your suggestion. Unfortunately, both did not fix my issue. The Error now changed to:

> Unhandled JS Exception: RNSound.setCategory is not a function

**Comment by benvium** [comment]
I presume you've run `react-native link react-native-sound`?

**Comment by jwilbert** [comment]
@benvium Yes, it was already linked. Seems like the version update actually did fix it. After another clean and build, everything works as it should. My bad. Thanks for your support!

**Comment by benvium** [comment]
Great stuff. Glad you got it going.
